"""
=============================================================================
eda_colab.py — EDA Notebook Code for Google Colab
Run this AFTER the EMR Spark pipeline completes successfully.
It downloads the processed Parquet files from S3 and shows the 3 EDA figures.
=============================================================================
"""

# ─── CELL 1: Install libraries ───────────────────────────────────────────────
# !pip install boto3 matplotlib pandas pyarrow fastparquet

# ─── CELL 2: AWS credentials ─────────────────────────────────────────────────
import os
os.environ["AWS_ACCESS_KEY_ID"]     = "YOUR_ACCESS_KEY"
os.environ["AWS_SECRET_ACCESS_KEY"] = "YOUR_SECRET_KEY"
os.environ["AWS_DEFAULT_REGION"]    = "us-east-1"

BUCKET = "25htc5-project-data-group31"

# ─── CELL 3: Download EDA figures that were already generated by EMR ─────────
import boto3

s3 = boto3.client("s3")

figures = ["eda/eda_figure_1.png", "eda/eda_figure_2.png", "eda/eda_figure_3.png"]

for key in figures:
    fname = key.split("/")[-1]
    s3.download_file(BUCKET, key, fname)
    print(f"Downloaded: {fname}")

# ─── CELL 4: Display the 3 EDA figures ───────────────────────────────────────
from IPython.display import Image, display

print("=" * 60)
print("EDA Figure 1 — Q&A Type, Skin Type, Budget Distribution")
print("=" * 60)
display(Image("eda_figure_1.png"))

print("=" * 60)
print("EDA Figure 2 — Train/Val/Test Split & Product Statistics")
print("=" * 60)
display(Image("eda_figure_2.png"))

print("=" * 60)
print("EDA Figure 3 — Output Quality & Purchase Verification")
print("=" * 60)
display(Image("eda_figure_3.png"))

# ─── CELL 5: Download a sample from processed/train for extra exploration ────
import pandas as pd

# Download sample_preview.jsonl (100 rows, created by the EMR pipeline)
s3.download_file(BUCKET, "processed/sample_preview.jsonl", "sample_preview.jsonl")
df = pd.read_json("sample_preview.jsonl", lines=True)

print(f"\nSample shape: {df.shape}")
print("\nColumns:", list(df.columns))
print("\nFirst record:")
print(df.iloc[0][["instruction", "output", "skin_type", "budget"]])

# ─── CELL 6: Quick extra plots from the sample ───────────────────────────────
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
fig.suptitle("Quick EDA from Training Sample (100 rows)", fontsize=12, fontweight="bold")

# Plot A: Q&A type distribution in sample
df["type"].value_counts().plot(kind="bar", ax=axes[0], color="#3498db", edgecolor="white")
axes[0].set_title("Q&A Type Distribution")
axes[0].set_xlabel("Type")
axes[0].tick_params(axis="x", rotation=30)

# Plot B: Skin type distribution in sample
df["skin_type"].value_counts().plot(kind="barh", ax=axes[1], color="#e74c3c")
axes[1].set_title("Skin Type Distribution")

# Plot C: Budget tier distribution in sample
df["budget"].value_counts().plot(kind="pie", ax=axes[2], autopct="%1.1f%%",
                                  colors=["#2ecc71", "#e67e22", "#3498db", "#9b59b6"])
axes[2].set_title("Budget Tier Distribution")
axes[2].set_ylabel("")

plt.tight_layout()
plt.savefig("eda_sample_extra.png", dpi=150, bbox_inches="tight")
plt.show()
print("Extra EDA plot saved as eda_sample_extra.png")
